import { AuthProvider } from "@/components/auth/AuthProvider";
import { Inter } from "next/font/google";
import { NavigationEvents } from "@/components/navigationEvent";
import Navbar  from "@/components/navBar"
import "./globals.css";
import "./DatePickerStyles.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          <NavigationEvents>
            {children}
          </NavigationEvents>
        </body>
        </html>
    </AuthProvider>
  );
}
